### ISSUE TITLE
No environment option available to set up the UDP protocol

### ISSUE THREAD

**Issue by VMax2** [Joentje/nordvpn-proxy#9] opened 2020-01-21 23:33 UTC
TCP protocol seems to be the default one and there is not the possibility to change it 

Following are the messages i hope will be fixed if possible:

Wed Jan 22 00:23:31 2020 NOTE: --fast-io is disabled since we are not using UDP

Tue Jan 21 23:32:36 2020 WARNING: --ping should normally be used with --ping-restart or --ping-exit,

Tue Jan 21 23:32:37 2020 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this,

It would be usefull to have an ENV variable to change the default two DNS as per users choice too
Thank you in advance

**Comment by Joentje** [comment] 2020-01-22 06:37
Thanks for creating an issue.

I have done some small changes. You can now use the UDP protocol as well. See #10 . To use it, use the latest tag: jeroenslot/nordvpn-proxy:latest. It will be released later.

For the DNS part, you want to set it yourself? You can already, see the readme: https://github.com/Joentje/nordvpn-proxy#start-container

**Comment by VMax2** [comment] 2020-01-22 11:33
Thank you for your quick reply, well, i didn't see previously the part about the PROTOCOL, i passed it at container creation with -e PROTOCOL="udp" but looking the log file the container stay still with the tcp , 

Wed Jan 22 12:12:32 2020 Attempting to establish TCP connection with [AF_INET]37.120.201.219:443 [nonblock]
Wed Jan 22 12:12:33 2020 TCP connection established with [AF_INET]37.120.201.219:443

same thing for the DNS , i changed the parameters as indicated, --dns=xxx.xxx.xxx.xx --dns=yyy.yyy.yyy.yyy  but don't seems to work, i see in the log the two DNS are still the default ones, 

"Wed Jan 22 12:12:34 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.7.0.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.7.0.9 255.255.255.0,peer-id 0,cipher AES-256-GCM' "

Thank you again for the support!!

**Comment by Joentje** [comment] 2020-01-22 16:52
No Problem, I see what the problem is. My fault :). 

Can you try again? Pull the latest: jeroenslot/nordvpn-proxy:latest again

**Comment by VMax2** [comment] 2020-01-22 22:08
Hi, now i can't start the container, when i pull the image with docker run -d etc etc , it pull the image, the container is created but when it start i have this error from bash:

docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"sudo\": executable file not found in $PATH": unknown.

:-)

**Comment by Joentje** [comment] 2020-01-23 18:15
I don't understand why its complaining about sudo. There is no sudo used.

Do you pass an extra command to the container?

**Comment by VMax2** [comment] 2020-01-23 21:42
No, just the indicated parameters... anyway, i deleted the image and pulled it again and now it work like a charm, don't know why but now the UDP protocol is working and the container too!!
What it's still not working is the dns change, i useded the --dns=xxx.xxx.xxx.xxx --dns=yyy.yyy.yyy.yyy at container creation but looking the log file i still find:
 
Thu Jan 23 22:14:00 2020 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.8.3.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.3.43 255.255.255.0,peer-id 42,cipher AES-256-GCM'

And of course the two minor things about the passwords cache and the ping told at the first post, but those are just for the perfection :-)

**Comment by Joentje** [comment] 2020-05-02 13:24
The UDP setting is now part of release 1.0.2 :)

**Comment by Joentje** [comment] 2020-07-26 15:05
If you still have issues, please create a new issue :)

**Closed by Joentje** 2020-07-26 15:05 UTC
